networks:
  kommunal-gpt-network:
    driver: bridge

services:
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    networks:
      - kommunal-gpt-network
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ${OLLAMA_IMAGE}:${OLLAMA_DOCKER_TAG}
    
  kommunal-gpt:
    image: ${WEBUI_IMAGE}:${WEBUI_TAG}
    networks:
      - kommunal-gpt-network
    restart: unless-stopped
    container_name: kommunal-gpt
    ports:
      - "${WEBUI_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./owui/data:/app/backend/data
      - ./owui/static:/app/build/static
    environment:
      - CUSTOM_NAME=${COMPAINION_NAME}
      - WEBUI_NAME=${COMPAINION_NAME}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - USE_CUDA_DOCKER=${USE_CUDA_DOCKER}
      - ENABLE_FOLLOW_UP_GENERATION=${ENABLE_FOLLOW_UP_GENERATION}

  compainion-ui:
    image: ${COMPAINION_UI_IMAGE}:${COMPAINION_UI_TAG}
    container_name: compainion-ui
    networks:
      - kommunal-gpt-network
    ports:
      - "${COMPAINION_UI_PORT}:80"
    volumes:
      - ./data:/app/data
    environment:
      - COMPAINION_UI_PORT=${COMPAINION_UI_PORT}
      - COMPAINION_UI_READONLY=${COMPAINION_UI_READONLY}
      - COMPAINION_UI_ADMIN_TOKEN=${COMPAINION_UI_ADMIN_TOKEN}
      - COMPAINION_NAME=${COMPAINION_NAME}
      - COMPAINION_DEFAULT_URL=${COMPAINION_DEFAULT_URL}
    restart: unless-stopped
    
  tika:
    container_name: tika
    image: ${TIKA_IMAGE}:${TIKA_TAG}
    restart: unless-stopped
    ports:
      - ${TIKA_PORT}:9998
    networks:
      - kommunal-gpt-network