name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (z.B. 1.2.3)'
        required: true
        default: '0.1.0'
      notes:
        description: 'Release Notes (optional)'
        required: false
        default: ''

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "TAG=v${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Prepare artifacts (ZIPs ohne Build)
        run: |
          mkdir -p artifacts
          zip -r "artifacts/KommunalGPT-windows-${{ github.event.inputs.version }}.zip" . -x "*.sh" ".git/*" ".github/*" "artifacts/*"
          zip -r "artifacts/KommunalGPT-linux-${{ github.event.inputs.version }}.zip" . -x "*.bat" ".git/*" ".github/*" "artifacts/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: KommunalGPT v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.notes }}
          draft: false
          prerelease: false
          files: |
            artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}